In [4]:
import requests
import pandas as pd

df = pd.read_csv('wpf_karnataka.csv')

In [5]:
df.head()

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
0,1994-01-15,Karnataka,Bangalore Urban,Bengaluru,12.962299,77.576943,cereals and tubers,Wheat,KG,actual,Retail,INR,7.0,0.2231
1,1994-03-15,Karnataka,Bangalore Urban,Bengaluru,12.962299,77.576943,cereals and tubers,Wheat,KG,actual,Retail,INR,6.5,0.2073
2,1994-04-15,Karnataka,Bangalore Urban,Bengaluru,12.962299,77.576943,cereals and tubers,Wheat,KG,actual,Retail,INR,6.5,0.2073
3,1994-05-15,Karnataka,Bangalore Urban,Bengaluru,12.962299,77.576943,cereals and tubers,Wheat,KG,actual,Retail,INR,4.0,0.1275
4,1994-07-15,Karnataka,Bangalore Urban,Bengaluru,12.962299,77.576943,cereals and tubers,Wheat,KG,actual,Retail,INR,6.8,0.2168